<?php

/**
 * @file
 * Contains drupal_migrate_demo.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function drupal_migrate_demo_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the drupal_migrate_demo module.
    case 'help.page.drupal_migrate_demo':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function drupal_migrate_demo_theme() {
  return [
    'drupal_migrate_demo' => [
      'render element' => 'children',
    ],
  ];
}
